"""Add transitions

Revision ID: 09898073b61c
Revises: b6c17d4641ae
Create Date: 2026-04-17 07:06:27.565186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09898073b61c'
down_revision: Union[str, Sequence[str], None] = 'b6c17d4641ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transition_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('target_hint_building_id', sa.String(length=50), nullable=True),
    sa.Column('target_hint_floor_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transition_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transition_groups_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transition_groups_id'), ['id'], unique=False)

    op.create_table('transition_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconstruction_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('target_hint_building_id', sa.String(length=50), nullable=True),
    sa.Column('target_hint_floor_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['transition_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reconstruction_id'], ['reconstructions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transition_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transition_points_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transition_points_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transition_points_reconstruction_id'), ['reconstruction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transition_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transition_points_reconstruction_id'))
        batch_op.drop_index(batch_op.f('ix_transition_points_id'))
        batch_op.drop_index(batch_op.f('ix_transition_points_group_id'))

    op.drop_table('transition_points')
    with op.batch_alter_table('transition_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transition_groups_id'))
        batch_op.drop_index(batch_op.f('ix_transition_groups_building_id'))

    op.drop_table('transition_groups')
    # ### end Alembic commands ###
