"""add building_id

Revision ID: b6c17d4641ae
Revises: 8a6fc82ae005
Create Date: 2026-03-30 13:03:09.295320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c17d4641ae'
down_revision: Union[str, Sequence[str], None] = '8a6fc82ae005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("UPDATE users SET full_name = 'Admin User' WHERE full_name IS NULL")
    op.execute("UPDATE users SET birth_date = '2000-01-01' WHERE birth_date IS NULL")
    op.execute("UPDATE users SET can_approve_users = FALSE WHERE can_approve_users IS NULL")

    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('full_name',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False,
                   existing_server_default=sa.text("'Admin User'"))
        batch_op.alter_column('birth_date',
                   existing_type=sa.DATE(),
                   nullable=False,
                   existing_server_default=sa.text("'2000-01-01'"))
        batch_op.alter_column('can_approve_users',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('can_approve_users',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
        batch_op.alter_column('birth_date',
                   existing_type=sa.DATE(),
                   nullable=True,
                   existing_server_default=sa.text("'2000-01-01'"))
        batch_op.alter_column('full_name',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True,
                   existing_server_default=sa.text("'Admin User'"))
    # ### end Alembic commands ###
